
import { Inter } from "next/font/google";
import "./globals.css";
// import 'bootstrap/dist/css/bootstrap.css'
import { UIProviders } from "./UIproviders";
import ReduxProvider from "@/lib/reduxProvider";
import CustomSessionProvider from "./CustomSessionProvider";
import Navbar from "./components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CustomSessionProvider>
      <html lang="en">
        <body className={inter.className}>
          <ReduxProvider>
            <UIProviders>
              <div className="min-h-full">
                <Navbar />
                {children}
              </div>
            </UIProviders>
          </ReduxProvider>
        </body>
      </html>
    </CustomSessionProvider>
  );
}
