export const rows = [
    {
        key: "1",
        doc_no: "QF4030001",
        request_date: "20/04/2544",
        request_by: "User",
        title: "Title",
        manager1: "Approved",
        manager2: "Approved",
        manager3: "Approved",
        status: "Approved",
    },
    {
        key: "2",
        doc_no: "QF4030002",
        request_date: "20/04/2544",
        request_by: "User",
        title: "Title",
        manager1: "Approved",
        manager2: "Approved",
        manager3: "Approved",
        status: "Approved",
    },
    {
        key: "3",
        doc_no: "QF4030001",
        request_date: "20/04/2544",
        request_by: "User",
        title: "Title",
        manager1: "Approved",
        manager2: "Approved",
        manager3: "",
        status: "Wait Approve",
    },
    {
        key: "4",
        doc_no: "QF4030001",
        request_date: "20/04/2544",
        request_by: "User",
        title: "Title",
        manager1: "Approved",
        manager2: "Approved",
        manager3: "Reject",
        status: "Reject",
    },
];